server:
  port: 8001
spring:
  elasticsearch:
    rest:
      uris: 127.0.0.1:9200

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/borrow?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis.xml


